package partitions

// FSType is a representation of the linux kernel filesystem types.
type FSType int64

var (
	ADFS_SUPER_MAGIC      FSType = 0xadf5
	AFFS_SUPER_MAGIC      FSType = 0xadff
	AFS_SUPER_MAGIC       FSType = 0x5346414f
	ANON_INODE_FS_MAGIC   FSType = 0x09041934
	AUTOFS_SUPER_MAGIC    FSType = 0x0187
	BDEVFS_MAGIC          FSType = 0x62646576
	BEFS_SUPER_MAGIC      FSType = 0x42465331
	BFS_MAGIC             FSType = 0x1badface
	BINFMTFS_MAGIC        FSType = 0x42494e4d
	BPF_FS_MAGIC          FSType = 0xcafe4a11
	BTRFS_SUPER_MAGIC     FSType = 0x9123683e
	BTRFS_TEST_MAGIC      FSType = 0x73727279
	CGROUP_SUPER_MAGIC    FSType = 0x27e0eb
	CGROUP2_SUPER_MAGIC   FSType = 0x63677270
	CIFS_MAGIC_NUMBER     FSType = 0xff534d42
	CODA_SUPER_MAGIC      FSType = 0x73757245
	COH_SUPER_MAGIC       FSType = 0x012ff7b7
	CRAMFS_MAGIC          FSType = 0x28cd3d45
	DEBUGFS_MAGIC         FSType = 0x64626720
	DEVFS_SUPER_MAGIC     FSType = 0x1373
	DEVPTS_SUPER_MAGIC    FSType = 0x1cd1
	ECRYPTFS_SUPER_MAGIC  FSType = 0xf15f
	EFIVARFS_MAGIC        FSType = 0xde5e81e4
	EFS_SUPER_MAGIC       FSType = 0x00414a53
	EXT_SUPER_MAGIC       FSType = 0x137d
	EXT2_OLD_SUPER_MAGIC  FSType = 0xef51
	EXT2_SUPER_MAGIC      FSType = 0xef53
	EXT3_SUPER_MAGIC      FSType = 0xef53
	EXT4_SUPER_MAGIC      FSType = 0xef53
	F2FS_SUPER_MAGIC      FSType = 0xf2f52010
	FUSE_SUPER_MAGIC      FSType = 0x65735546
	FUTEXFS_SUPER_MAGIC   FSType = 0xbad1dea
	HFS_SUPER_MAGIC       FSType = 0x4244
	HOSTFS_SUPER_MAGIC    FSType = 0x00c0ffee
	HPFS_SUPER_MAGIC      FSType = 0xf995e849
	HUGETLBFS_MAGIC       FSType = 0x958458f6
	ISOFS_SUPER_MAGIC     FSType = 0x9660
	JFFS2_SUPER_MAGIC     FSType = 0x72b6
	JFS_SUPER_MAGIC       FSType = 0x3153464a
	MINIX_SUPER_MAGIC     FSType = 0x137f
	MINIX_SUPER_MAGIC2    FSType = 0x138f
	MINIX2_SUPER_MAGIC    FSType = 0x2468
	MINIX2_SUPER_MAGIC2   FSType = 0x2478
	MINIX3_SUPER_MAGIC    FSType = 0x4d5a
	MQUEUE_MAGIC          FSType = 0x19800202
	MSDOS_SUPER_MAGIC     FSType = 0x4d44
	MTD_INODE_FS_MAGIC    FSType = 0x11307854
	NCP_SUPER_MAGIC       FSType = 0x564c
	NFS_SUPER_MAGIC       FSType = 0x6969
	NILFS_SUPER_MAGIC     FSType = 0x3434
	NSFS_MAGIC            FSType = 0x6e736673
	NTFS_SB_MAGIC         FSType = 0x5346544e
	OCFS2_SUPER_MAGIC     FSType = 0x7461636f
	OPENPROM_SUPER_MAGIC  FSType = 0x9fa1
	OVERLAYFS_SUPER_MAGIC FSType = 0x794c7630
	PIPEFS_MAGIC          FSType = 0x50495045
	PROC_SUPER_MAGIC      FSType = 0x9fa0
	PSTOREFS_MAGIC        FSType = 0x6165676c
	QNX4_SUPER_MAGIC      FSType = 0x002f
	QNX6_SUPER_MAGIC      FSType = 0x68191122
	RAMFS_MAGIC           FSType = 0x858458f6
	REISERFS_SUPER_MAGIC  FSType = 0x52654973
	ROMFS_MAGIC           FSType = 0x7275
	SECURITYFS_MAGIC      FSType = 0x73636673
	SELINUX_MAGIC         FSType = 0xf97cff8c
	SMACK_MAGIC           FSType = 0x43415d53
	SMB_SUPER_MAGIC       FSType = 0x517b
	SMB2_MAGIC_NUMBER     FSType = 0xfe534d42
	SOCKFS_MAGIC          FSType = 0x534f434b
	SQUASHFS_MAGIC        FSType = 0x73717368
	SYSFS_MAGIC           FSType = 0x62656572
	SYSV2_SUPER_MAGIC     FSType = 0x012ff7b6
	SYSV4_SUPER_MAGIC     FSType = 0x012ff7b5
	TMPFS_MAGIC           FSType = 0x01021994
	TRACEFS_MAGIC         FSType = 0x74726163
	UDF_SUPER_MAGIC       FSType = 0x15013346
	UFS_MAGIC             FSType = 0x00011954
	USBDEVICE_SUPER_MAGIC FSType = 0x9fa2
	V9FS_MAGIC            FSType = 0x01021997
	VXFS_SUPER_MAGIC      FSType = 0xa501fcf5
	XENFS_SUPER_MAGIC     FSType = 0xabba1974
	XENIX_SUPER_MAGIC     FSType = 0x012ff7b4
	XFS_SUPER_MAGIC       FSType = 0x58465342
	_XIAFS_SUPER_MAGIC    FSType = 0x012fd16d
)

// Name returns the human-readable name of the kernel filesystems.
func (fsType FSType) Name() string {
	switch fsType {
	case ADFS_SUPER_MAGIC:
		return "ADFS_SUPER_MAGIC"
	case AFFS_SUPER_MAGIC:
		return "AFFS_SUPER_MAGIC"
	case AFS_SUPER_MAGIC:
		return "AFS_SUPER_MAGIC"
	case ANON_INODE_FS_MAGIC:
		return "ANON_INODE_FS_MAGIC INODE"
	case AUTOFS_SUPER_MAGIC:
		return "AUTOFS_SUPER_MAGIC"
	case BDEVFS_MAGIC:
		return "BDEVFS_MAGIC"
	case BEFS_SUPER_MAGIC:
		return "BEFS_SUPER_MAGIC"
	case BFS_MAGIC:
		return "BFS_MAGIC"
	case BINFMTFS_MAGIC:
		return "BINFMTFS_MAGIC"
	case BPF_FS_MAGIC:
		return "BPF_FS_MAGIC"
	case BTRFS_SUPER_MAGIC:
		return "BTRFS_SUPER_MAGIC"
	case BTRFS_TEST_MAGIC:
		return "BTRFS_TEST_MAGIC"
	case CGROUP_SUPER_MAGIC:
		return "CGROUP_SUPER_MAGIC"
	case CGROUP2_SUPER_MAGIC:
		return "CGROUP2_SUPER_MAGIC"
	case CIFS_MAGIC_NUMBER:
		return "CIFS_MAGIC_NUMBER"
	case CODA_SUPER_MAGIC:
		return "CODA_SUPER_MAGIC"
	case COH_SUPER_MAGIC:
		return "COH_SUPER_MAGIC"
	case CRAMFS_MAGIC:
		return "CRAMFS_MAGIC"
	case DEBUGFS_MAGIC:
		return "DEBUGFS_MAGIC"
	case DEVFS_SUPER_MAGIC:
		return "DEVFS_SUPER_MAGIC"
	case DEVPTS_SUPER_MAGIC:
		return "DEVPTS_SUPER_MAGIC"
	case ECRYPTFS_SUPER_MAGIC:
		return "ECRYPTFS_SUPER_MAGIC"
	case EFIVARFS_MAGIC:
		return "EFIVARFS_MAGIC"
	case EFS_SUPER_MAGIC:
		return "EFS_SUPER_MAGIC"
	case EXT_SUPER_MAGIC:
		return "EXT_SUPER_MAGIC"
	case EXT2_OLD_SUPER_MAGIC:
		return "EXT2_OLD_SUPER_MAGIC"
	case EXT2_SUPER_MAGIC:
		return "EXT2_SUPER_MAGIC"
	case EXT3_SUPER_MAGIC:
		return "EXT3_SUPER_MAGIC"
	case EXT4_SUPER_MAGIC:
		return "EXT4_SUPER_MAGIC"
	case F2FS_SUPER_MAGIC:
		return "F2FS_SUPER_MAGIC"
	case FUSE_SUPER_MAGIC:
		return "FUSE_SUPER_MAGIC"
	case FUTEXFS_SUPER_MAGIC:
		return "FUTEXFS_SUPER_MAGIC"
	case HFS_SUPER_MAGIC:
		return "HFS_SUPER_MAGIC"
	case HOSTFS_SUPER_MAGIC:
		return "HOSTFS_SUPER_MAGIC"
	case HPFS_SUPER_MAGIC:
		return "HPFS_SUPER_MAGIC"
	case HUGETLBFS_MAGIC:
		return "HUGETLBFS_MAGIC"
	case ISOFS_SUPER_MAGIC:
		return "ISOFS_SUPER_MAGIC"
	case JFFS2_SUPER_MAGIC:
		return "JFFS2_SUPER_MAGIC"
	case JFS_SUPER_MAGIC:
		return "JFS_SUPER_MAGIC"
	case MINIX_SUPER_MAGIC:
		return "MINIX_SUPER_MAGIC"
	case MINIX_SUPER_MAGIC2:
		return "MINIX_SUPER_MAGIC2"
	case MINIX2_SUPER_MAGIC:
		return "MINIX2_SUPER_MAGIC"
	case MINIX2_SUPER_MAGIC2:
		return "MINIX2_SUPER_MAGIC2"
	case MINIX3_SUPER_MAGIC:
		return "MINIX3_SUPER_MAGIC"
	case MQUEUE_MAGIC:
		return "MQUEUE_MAGIC"
	case MSDOS_SUPER_MAGIC:
		return "MSDOS_SUPER_MAGIC"
	case MTD_INODE_FS_MAGIC:
		return "MTD_INODE_FS_MAGIC"
	case NCP_SUPER_MAGIC:
		return "NCP_SUPER_MAGIC"
	case NFS_SUPER_MAGIC:
		return "NFS_SUPER_MAGIC"
	case NILFS_SUPER_MAGIC:
		return "NILFS_SUPER_MAGIC"
	case NSFS_MAGIC:
		return "NSFS_MAGIC"
	case NTFS_SB_MAGIC:
		return "NTFS_SB_MAGIC"
	case OCFS2_SUPER_MAGIC:
		return "OCFS2_SUPER_MAGIC"
	case OPENPROM_SUPER_MAGIC:
		return "OPENPROM_SUPER_MAGIC"
	case OVERLAYFS_SUPER_MAGIC:
		return "OVERLAYFS_SUPER_MAGIC"
	case PIPEFS_MAGIC:
		return "PIPEFS_MAGIC"
	case PROC_SUPER_MAGIC:
		return "PROC_SUPER_MAGIC"
	case PSTOREFS_MAGIC:
		return "PSTOREFS_MAGIC"
	case QNX4_SUPER_MAGIC:
		return "QNX4_SUPER_MAGIC"
	case QNX6_SUPER_MAGIC:
		return "QNX6_SUPER_MAGIC"
	case RAMFS_MAGIC:
		return "RAMFS_MAGIC"
	case REISERFS_SUPER_MAGIC:
		return "REISERFS_SUPER_MAGIC"
	case ROMFS_MAGIC:
		return "ROMFS_MAGIC"
	case SECURITYFS_MAGIC:
		return "SECURITYFS_MAGIC"
	case SELINUX_MAGIC:
		return "SELINUX_MAGIC"
	case SMACK_MAGIC:
		return "SMACK_MAGIC"
	case SMB_SUPER_MAGIC:
		return "SMB_SUPER_MAGIC"
	case SMB2_MAGIC_NUMBER:
		return "SMB2_MAGIC_NUMBER"
	case SOCKFS_MAGIC:
		return "SOCKFS_MAGIC"
	case SQUASHFS_MAGIC:
		return "SQUASHFS_MAGIC"
	case SYSFS_MAGIC:
		return "SYSFS_MAGIC"
	case SYSV2_SUPER_MAGIC:
		return "SYSV2_SUPER_MAGIC"
	case SYSV4_SUPER_MAGIC:
		return "SYSV4_SUPER_MAGIC"
	case TMPFS_MAGIC:
		return "TMPFS_MAGIC"
	case TRACEFS_MAGIC:
		return "TRACEFS_MAGIC"
	case UDF_SUPER_MAGIC:
		return "UDF_SUPER_MAGIC"
	case UFS_MAGIC:
		return "UFS_MAGIC"
	case USBDEVICE_SUPER_MAGIC:
		return "USBDEVICE_SUPER_MAGIC"
	case V9FS_MAGIC:
		return "V9FS_MAGIC"
	case VXFS_SUPER_MAGIC:
		return "VXFS_SUPER_MAGIC"
	case XENFS_SUPER_MAGIC:
		return "XENFS_SUPER_MAGIC"
	case XENIX_SUPER_MAGIC:
		return "XENIX_SUPER_MAGIC"
	case XFS_SUPER_MAGIC:
		return "XFS_SUPER_MAGIC"
	case _XIAFS_SUPER_MAGIC:
		return "_XIAFS_SUPER_MAGIC"
	default:
		return "UNKNOWN"
	}
}
